<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE faq [
		<!ELEMENT faq (item)*>
		<!ELEMENT item (question|answer)*>
		<!ELEMENT question (#PCDATA)>
		<!ELEMENT answer (#PCDATA)>
		]>
<faq>
	<item>
		<question>
			What is Lorem Ipsum?
		</question>
		<answer>
			Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
		</answer>
	</item>
	<item>
		<question>
			Where does it come from?
		</question>
		<answer>
			Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.

			The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.
		</answer>
	</item>
	<item>
		<question>
			Why do we use it?
		</question>
		<answer>
			It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
		</answer>
	</item>
	<item>
		<question>
			Where can I get some?
		</question>
		<answer>
			There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
		</answer>
	</item>
</faq>